/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_manuelvalladares;

import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author mevl1
 */
public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PROYECTOS = new javax.swing.JDialog();
        tf_nombre_proyecto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        ACTIVIDAD = new javax.swing.JDialog();
        tf_nom_act = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_dur_act = new javax.swing.JTextField();
        tf_ret_act = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cb_act_predecesora = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_proyectos_actividades = new javax.swing.JComboBox<>();
        HILO = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cb_pro = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        cb_proyectos_principal = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jButton5.setText("Crear");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PROYECTOSLayout = new javax.swing.GroupLayout(PROYECTOS.getContentPane());
        PROYECTOS.getContentPane().setLayout(PROYECTOSLayout);
        PROYECTOSLayout.setHorizontalGroup(
            PROYECTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PROYECTOSLayout.createSequentialGroup()
                .addGroup(PROYECTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PROYECTOSLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(tf_nombre_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PROYECTOSLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton5)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        PROYECTOSLayout.setVerticalGroup(
            PROYECTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PROYECTOSLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PROYECTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_nombre_proyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(25, 25, 25))
        );

        jLabel2.setText("Nombre");

        jLabel3.setText("Duracion");

        jLabel4.setText("Posibilidad de retraso");

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel5.setText("Actividad predecesora");

        jLabel6.setText("Proyecto");

        cb_proyectos_actividades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_proyectos_actividadesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout ACTIVIDADLayout = new javax.swing.GroupLayout(ACTIVIDAD.getContentPane());
        ACTIVIDAD.getContentPane().setLayout(ACTIVIDADLayout);
        ACTIVIDADLayout.setHorizontalGroup(
            ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACTIVIDADLayout.createSequentialGroup()
                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ACTIVIDADLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ACTIVIDADLayout.createSequentialGroup()
                                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_dur_act, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nom_act, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ACTIVIDADLayout.createSequentialGroup()
                                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ACTIVIDADLayout.createSequentialGroup()
                                        .addComponent(cb_act_predecesora, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tf_ret_act)
                                    .addComponent(cb_proyectos_actividades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(ACTIVIDADLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        ACTIVIDADLayout.setVerticalGroup(
            ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACTIVIDADLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nom_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_dur_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_ret_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_proyectos_actividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ACTIVIDADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_act_predecesora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton6.setText("ejecutar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("mostrar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HILOLayout = new javax.swing.GroupLayout(HILO.getContentPane());
        HILO.getContentPane().setLayout(HILOLayout);
        HILOLayout.setHorizontalGroup(
            HILOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HILOLayout.createSequentialGroup()
                .addGroup(HILOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HILOLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HILOLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(cb_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(HILOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6)
                            .addComponent(jButton7))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        HILOLayout.setVerticalGroup(
            HILOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HILOLayout.createSequentialGroup()
                .addGroup(HILOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(HILOLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(cb_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HILOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_proyectos_principal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_proyectos_principalItemStateChanged(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Proyecto");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jButton1.setText("Crear Actividades");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Proyecto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton4.setText("EJECUTAR");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(cb_proyectos_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_proyectos_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton4)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        PROYECTOS.setModal(true);
        PROYECTOS.pack();
        PROYECTOS.setLocationRelativeTo(this);
        PROYECTOS.setVisible(true);


    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        PROYECTO proy = new PROYECTO(tf_nombre_proyecto.getText(), 0, jTree1,
                (DefaultComboBoxModel) cb_proyectos_principal.getModel(), (DefaultComboBoxModel) cb_act_predecesora.getModel());
        DefaultComboBoxModel modelo=(DefaultComboBoxModel)cb_proyectos_principal.getModel();
        
        modelo.addElement(proy);
        cb_proyectos_principal.setModel(modelo);
        cb_proyectos_actividades.setModel(modelo);
        cb_pro.setModel(modelo);
        proy.setCombo(modelo);
        proyectos.add(proy);
//  
       
       
    }//GEN-LAST:event_jButton5MouseClicked

    private void cb_proyectos_principalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_proyectos_principalItemStateChanged
        // TODO add your handling code here:
        PROYECTO pr=(PROYECTO) cb_proyectos_principal.getSelectedItem();
          DefaultTreeModel m = (DefaultTreeModel) jTree1.getModel();
        m.setRoot(new DefaultMutableTreeNode(cb_proyectos_principal.getSelectedItem().toString()));
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) m.getRoot();
        ruta = pr.getActividades().toString();
        arbol(pr.getActividades(), n);

    }//GEN-LAST:event_cb_proyectos_principalItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here

        PROYECTO temp = null;
        ACTIVIDAD.setModal(true);
        ACTIVIDAD.pack();
        ACTIVIDAD.setLocationRelativeTo(this);
        ACTIVIDAD.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        //String nombre, int inicio_temprano, int duracion, int final_temprano, ACTIVIDADES actividades_predecesoras, ACTIVIDADES actividades_sucesoras, int retraso
        int inicio_temp=1,duracion=Integer.parseInt(tf_dur_act.getText()),final_temprano=inicio_temp+duracion;
        if (cb_act_predecesora.getSelectedItem()==null) {
       PROYECTO temp = (PROYECTO) cb_proyectos_actividades.getSelectedItem();
       DefaultComboBoxModel m=(DefaultComboBoxModel)cb_act_predecesora.getModel();
        ACTIVIDADES acts = new ACTIVIDADES(tf_nom_act.getText(),inicio_temp,duracion,final_temprano,Integer.parseInt(tf_ret_act.getText()),null);
        temp.getActividades().add(acts);
            Activi.add(acts);
        }else{
          PROYECTO temp = (PROYECTO) cb_proyectos_actividades.getSelectedItem();
           ACTIVIDADES acts = new ACTIVIDADES(tf_nom_act.getText(),inicio_temp,duracion,final_temprano,Integer.parseInt(tf_ret_act.getText()), (PROYECTO) cb_proyectos_actividades.getSelectedItem());
          Activi.add(acts);
           temp.getActividades().add(acts);
           int mayor=0;
            for (ACTIVIDADES i : temp.getActividades()) {
                if (i.getInicio_temprano()>mayor) {
                    mayor=i.getFinal_temprano();
                    System.out.println(mayor);
                }
            }
            acts.setInicio_temprano(mayor+1);
            acts.setFinal_temprano(mayor+duracion);
           
            System.out.println(temp.getActividades().get(cb_act_predecesora.getSelectedIndex()).getInicio_temprano());
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void cb_proyectos_actividadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_proyectos_actividadesItemStateChanged
        // TODO add your handling code here:
       PROYECTO temp = (PROYECTO) cb_proyectos_actividades.getSelectedItem();
           cb_act_predecesora.removeAllItems();
           DefaultComboBoxModel m=(DefaultComboBoxModel)cb_act_predecesora.getModel();
           for (Object i : temp.getActividades()) {
            m.addElement(i);
        }
cb_act_predecesora.setModel(m);

    }//GEN-LAST:event_cb_proyectos_actividadesItemStateChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        HILO.setModal(true);
        HILO.pack();
        HILO.setLocationRelativeTo(this);
        HILO.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
           PROYECTO P = (PROYECTO) cb_pro.getSelectedItem();
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        m.setRowCount(0);
        cargar(P.getActividades());
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
             PROYECTO P = (PROYECTO) cb_pro.getSelectedItem();
        pos = 0;
        try {
            correr(P.getActividades());
        } catch (InterruptedException ex) {
        }
        
        
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ACTIVIDAD;
    private javax.swing.JDialog HILO;
    private javax.swing.JDialog PROYECTOS;
    private javax.swing.JComboBox<String> cb_act_predecesora;
    private javax.swing.JComboBox<String> cb_pro;
    private javax.swing.JComboBox<String> cb_proyectos_actividades;
    private javax.swing.JComboBox<String> cb_proyectos_principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField tf_dur_act;
    private javax.swing.JTextField tf_nom_act;
    private javax.swing.JTextField tf_nombre_proyecto;
    private javax.swing.JTextField tf_ret_act;
    // End of variables declaration//GEN-END:variables
ArrayList<PROYECTO> proyectos = new ArrayList();
 ArrayList<ACTIVIDADES> Activi = new ArrayList();
    DefaultMutableTreeNode nodo;
    String ruta="";
    int pos = 0;
     HILO A = null;
    HILO B = null;
    private void arbol(ArrayList<ACTIVIDADES> Root, DefaultMutableTreeNode nodo) {
        try {
            for (ACTIVIDADES temp : Root) {
                if (temp.getActividades_predecesoras().isEmpty()) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getNombre());
                    nodo.add(n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getNombre());
                    nodo.add(n);
                    arbol(temp.getActividades_predecesoras(), n);
                }
                if (Root.toString().equals(ruta)) {
                }
            }
        } catch (Exception e) {
        }
    }
     public void cargar(ArrayList<ACTIVIDADES> P) {
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        for (ACTIVIDADES act : P) {
            if (act.getActividades_sucesoras().isEmpty()) {
                Object[] R = {act.getNombre(), act.getDuracion(), "En Espera."};
                m.addRow(R);
            } else {
                Object[] R = {act.getNombre(), act.getDuracion(), "En Espera."};
                m.addRow(R);
                cargar(act.getActividades_sucesoras());
            }
        }
    }
         public void correr(ArrayList<ACTIVIDADES> P) throws InterruptedException {
        for (ACTIVIDADES act : P) {
            B = new HILO(act, jTable1, pos);
            B.start();
            ++pos;
        }
        B.join();

        for (ACTIVIDADES act : P) {
            for (ACTIVIDADES act2 : act.getActividades_sucesoras()) {
                if (act.getActividades_sucesoras().isEmpty()) {
                    break;
                } else {
                    B = new HILO(act, jTable1, pos);
                    B.start();
                    ++pos;
                }
                B.join();
                correr(act2.getActividades_sucesoras());
            }

        }
}
}